# Generated by Django 5.1.7 on 2026-08-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='messaging_m_group_i_3752e2_idx',
            old_name='messaging_m_group_i_idx',
        ),
    ]
